services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-api-gateway
    ports:
      - "${SERVER_PORT:-8989}:${SERVER_PORT:-8989}"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - SERVER_PORT=${SERVER_PORT:-8989}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - scholarai-network
    restart: unless-stopped
    # Will connect to existing service-registry via network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8989}/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Note: service-registry is already running from the main orchestration
# This service will connect to the existing service-registry container

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
