spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Global CORS configuration for Spring Cloud Gateway (WebFlux)
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "https://localhost:3000"
              - "http://127.0.0.1:3000"
              - "https://127.0.0.1:3000"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers: "*"

      httpclient:
        response-timeout: 60000
        connect-timeout: 30000
        pool:
          max-idle-time: PT15S
          max-life-time: PT60S

  cache:
    type: caffeine

  codec:
    max-in-memory-size: 10MB

server:
  port: 8989

# Eureka Client Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:api-gateway}
    appname: api-gateway

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none